version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file: .env.example
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3000:3000"
    env_file: .env.example
    depends_on:
      - api
