version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file: .env.example
    profiles: ["demo"]
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3000:3000"
    env_file: .env.example
    depends_on:
      - api
    profiles: ["demo"]
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: loto
      POSTGRES_USER: loto
      POSTGRES_PASSWORD: loto
    ports:
      - "5432:5432"
    profiles: ["pilot"]
