name: CI

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-cov
          pnpm install --frozen-lockfile
          pre-commit install
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Lint
        run: make lint
      - name: Type check
        run: make typecheck
      - name: Tests
        run: |
          PYTEST_ADDOPTS="--cov=loto --cov=apps/api --cov-report=xml" make test
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: api
          fail_ci_if_error: true

  ui-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -C apps/maximo-extension-ui build
      - name: Unit tests
        run: pnpm -C apps/maximo-extension-ui test

  ui-e2e:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.41.0-jammy
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -C apps/maximo-extension-ui build
      - name: Start UI
        run: |
          pnpm -C apps/maximo-extension-ui start &
          for i in {1..30}; do
            curl -fsS http://localhost:3000 && break
            sleep 2
          done
      - name: E2E tests
        run: pnpm -C apps/maximo-extension-ui exec playwright test --headed

  publish:
    runs-on: ubuntu-latest
    needs: [api, ui-unit, ui-e2e]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ghcr.io/${{ github.repository }}-api:${{ github.ref_name }}
      - name: Build UI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ui
          push: true
          tags: ghcr.io/${{ github.repository }}-ui:${{ github.ref_name }}
