name: CI

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pre-commit install
      - name: Dependency vulnerability scan
        run: |
          pip install pip-audit
          pip-audit
          pnpm audit --audit-level=high
      - name: Frontend build and test
        run: |
          pnpm -C apps/maximo-extension-ui i
          pnpm -C apps/maximo-extension-ui build
          pnpm -C apps/maximo-extension-ui test
      - name: Lint
        run: make lint
      - name: Type check
        run: make typecheck
      - name: Tests
        run: make test
