name: Weekly KPI Report

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Generate report
        run: |
          python -m apps.api.reporting
      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report
          path: reports/
